name: Trigger Auto Merge

on:
  push:
    branches:
      - metadata  # Trigger only on the 'metadata' branch
    paths:
      - 'executions/**/test-report.html'  # File path pattern for test-report.html

jobs:
  process-test-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # For debugging purpose
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
        list-files: shell

        # Detect changes against the most recent commit on the same branch before the push
        base: ${{ github.ref }}

        # Only filters added or modified files.
        filters: |
          test_report:
            - added|modified: 'executions/**/test-report.html'

    - name: Print File
      if: ${{ steps.filter.outputs.test_report == 'true' }}
      run: echo ${{ steps.filter.outputs.test_report_files }}
