name: Trigger Auto Merge

on:
  push:
    branches:
      - metadata  # Trigger only on the 'metadata' branch
    paths:
      - 'executions/**/test-report.html'  # File path pattern for test-report.html

jobs:
  process-test-report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
        list-files: shell

        # In this example changed files will be checked by linter.
        # It doesn't make sense to lint deleted files.
        # Therefore we specify we are only interested in added or modified files.
        filters: |
          test-report:
            - added|modified: 'executions/**/test-report.html'

    - name: Print File
      if: ${{ steps.filter.outputs.test-report == 'true' }}
      run: npx textlint ${{ steps.filter.outputs.markdown_files }}
